version: '2'
services:
  chatapp:
    build: .
    ports:
    - "9000:9000"
    volumes:
    - ".:/code"
    links:
    - redis
    stdin_open: true
    tty: true
  redis:
    image: redis
    ports:
      - "6379:6379"