version: '2'
services:
  chatapp:
    build: .
    ports:
    - "9000:9000"
    volumes:
    - ".:/code"
    stdin_open: true
    tty: true
    links:
    - redis
  redis:
    image: redis
    ports:
      - "6379:6379"